### PR TITLE
Adding social sharing using Telegram

### PR DESCRIPTION
**Pull request by pfmephisto**
This add the ability to share links using telegram.me. It's an adaptation of the other social sharing plugins, just rewritten to use telegram.me share links.

### CODE REVIEW

**Comment by pfmephisto** [comment]
Should I sign off on the commits and make a new pull request?
Seems I'm new to how this works.

**Comment by rullzer** [comment]
Yes please sign your commits.  See https://github.com/nextcloud/socialsharing/pull/40/checks?check_run_id=568598711 on how to

**Review by rullzer — APPROVED** [review]
Fine by me :)
Didn't test as I do not have telegram

**Comment by rullzer** [comment]
Now feel free to register the app on apps.nxtcloud.com so you can release it.
I can add you as a maintainer here.

**Pull request merged**
