### PR TITLE
Make social sharing apps compatible with 14

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by JSoko** [comment]
Why isn't this app in the store marked as NC14-compatible? Or did I miss something?

**Comment by MorrisJobke** [comment]
> Why isn't this app in the store marked as NC14-compatible? Or did I miss something?

I guess they weren't uploaded yet. 🙈 

@schiessle @nickvergessen mind to do it?

**Comment by rullzer** [comment]
already done.https://apps.nextcloud.com/apps/socialsharing_twitter

**Comment by JSoko** [comment]
Yes, was made right after my question on Sept. 6th. Thanks!

**Pull request merged**
